imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: framework.yml }
    - { resource: twig.yml }
    - { resource: assetic.yml }
    - { resource: doctrine.yml }
    - { resource: swiftmailer.yml }
    - { resource: fos_user.yml }
    - { resource: sp_bower.yml }
    - { resource: stof_doctrine_extensions.yml }
