sensio_framework_extra:
    view:
        annotations: false

fos_rest:
    view:
        view_response_listener: true
        formats:
            json: true
            rss: false # removing them will also work
            xml: true