fos_oauth_server:
    db_driver: orm       # Driver availables: orm, mongodb, or propel
    client_class:        Sb\AppBundle\Entity\Oauth\Client
    access_token_class:  Sb\AppBundle\Entity\Oauth\AccessToken
    refresh_token_class: Sb\AppBundle\Entity\Oauth\RefreshToken
    auth_code_class:     Sb\AppBundle\Entity\Oauth\AuthCode
    service:
        user_provider: fos_user.user_manager
